src/DemoGit.Presentation/Controllers/CompraEfetivadaController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using DemoGit.Infrastructure.Context.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace DemoGit.Presentation.Controllers
{
    [Authorize]
    public class CompraEfetivadaController : Controller
    {
        private readonly ILogger<CompraEfetivadaController> _logger;
        private readonly ICompraEfetivadaRepository _repository;
        private readonly IProdutoRepository _produtoRepository;
        private readonly IUsuarioRepository _usuarioRepository;

        public CompraEfetivadaController(ILogger<CompraEfetivadaController> logger, ICompraEfetivadaRepository repository, IProdutoRepository produtoRepository, IUsuarioRepository usuarioRepository)
        {
            _logger = logger;
            _repository = repository;
            _produtoRepository = produtoRepository;
            _usuarioRepository = usuarioRepository;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult CarregarListaCompraEfetivadaIndex()
        {
            var listObj = new List<object>();

            foreach (var compra in _repository.SelectAll())
            {
                var prod = _produtoRepository.SelectById(compra.ProdutoId ?? "");
                var usuarioCompra = _usuarioRepository.SelectById(compra.UsuarioId ?? "");

                listObj.Add(new
                {
                    ProdutoDescricao = prod.Descricao,
                    ProdutoImagem = prod.Imagem,
                    UsuarioCompra = usuarioCompra?.FullName ?? "",
                    ValorTotal = compra.ValorTotal,
                    ProdutoPreco = prod.Preco,
                    QuantidadeCompra = compra.QuantidadeCompra,
                    DataCompra = compra.DataCompra
                });
            }

            return Json(new { compra = listObj });
        }
    }
}

src/DemoGit.Presentation/Controllers/ProdutoController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using DemoGit.Domain.Entities;
using DemoGit.Infrastructure.Context.Interfaces;
using Hanssens.Net;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MongoDB.Bson;

namespace DemoGit.Presentation.Controllers;

[Authorize]
public class ProdutoController : Controller
{

    private readonly ILogger<ProdutoController> _logger;
    private readonly IProdutoRepository _repository;
    private readonly ICompraEfetivadaRepository _compraEfetivadaRepository;
    private readonly IResourceRepository _resourceRepository;
    private readonly IUsuarioRepository _usuarioRepository;

    public ProdutoController(ILogger<ProdutoController> logger, IProdutoRepository repository, ICompraEfetivadaRepository compraEfetivadaRepository, IResourceRepository resourceRepository, IUsuarioRepository usuarioRepository)
    {
        _logger = logger;
        _repository = repository;
        _compraEfetivadaRepository = compraEfetivadaRepository;
        _resourceRepository = resourceRepository;
        _usuarioRepository = usuarioRepository;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult ListaFavoritos()
    {
        return View();
    }

    public IActionResult Inserir()
    {
        return View();
    }

    public IActionResult CarregarListaProdutosIndex()
    {
        var listProdutos = _repository.SelectAll();

        using (var storage = new LocalStorage())
        {
            foreach (var prod in listProdutos)
            {
                prod.IsFavoritado = storage.Exists(prod.Id);
            }
        }

        return Json(new { produtos = listProdutos, resourceImages = _resourceRepository.GetImages() });
    }

    [HttpPost]
    public IActionResult Inserir(
                                    [Bind("Descricao, Preco, QuantidadeEstoque, ArquivoImagem")]
                                    Produto model
                                )
    {
        if (ModelState.IsValid)
        {
            _repository.Create(model);

            return RedirectToAction("Index");
        }

        return View(model);
    }

    public IActionResult Editar(string id)
    {
        return View(_repository.SelectById(id));
    }

    [HttpPost]
    public IActionResult Editar(Produto model)
    {
        if (ModelState.IsValid)
        {
            _repository.Update(model);

            return RedirectToAction("Index");
        }

        return View(model);
    }

    public IActionResult Deletar(string id)
    {
        return View(_repository.SelectById(id));
    }

    [HttpPost]
    public IActionResult Deletar(Produto model)
    {
        _repository.DeleteById(model.Id ?? "");

        return RedirectToAction("Index");
    }

    public IActionResult Comprar(string id)
    {
        var produto = _repository.SelectById(id);

        ViewBag.CompraProdutoDescricao = produto.Descricao;
        ViewBag.CompraProdutoPreco = produto.Preco;
        ViewBag.CompraProdutoQuantidadeEstoque = produto.QuantidadeEstoque;

        return View(new CompraEfetivada { ProdutoId = produto.Id });
    }

    [HttpPost]
    public IActionResult Comprar(CompraEfetivada model)
    {
        var produto = _repository.SelectById(model.ProdutoId ?? "");

        if (produto.QuantidadeEstoque < model.QuantidadeCompra)
        {
            ModelState.AddModelError("CompraNaoPermitida", "Este produto não possui mais estoque para sua compra!");
            return View(model);
        }

        //Por algum motivo desconhecido o Id estava sendo copiado a partir do ProdutoId
        model.Id = ObjectId.GenerateNewId().ToString();
        model.ValorTotal = (produto.Preco ?? 0) * model.QuantidadeCompra;
        model.DataCompra = DateTime.Now;

        var usuarioAtual = _usuarioRepository.SelectByUsername(User!.Identity!.Name);
        model.UsuarioId = usuarioAtual.Id;

        _compraEfetivadaRepository.Create(model);

        produto.QuantidadeEstoque -= model.QuantidadeCompra;
        _repository.Update(produto);

        return RedirectToAction("Index");
    }

    [HttpGet]
    public IActionResult FavoritarProduto(string id, string nameActionRedirect)
    {
        using (var storage = new LocalStorage())
        {
            if (storage.Exists(id))
            {
                storage.Remove(id);
            }
            else
            {
                storage.Store(id, true);
            }
        }

        return RedirectToAction(nameActionRedirect);
    }

    public IActionResult CarregarListaProdutosFavoritados()
    {
        var products = _repository.SelectAll();
        var listProdutos = new List<Produto>();

        using (var storage = new LocalStorage())
        {
            foreach (var prod in products)
                if (storage.Exists(prod.Id))
                    listProdutos.Add(prod);
        }

        return Json(new { produtos = listProdutos });
    }
}

src/DemoGit.Presentation/Controllers/UsuarioController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using DemoGit.Domain.Entities;
using DemoGit.Infrastructure.Context.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace DemoGit.Presentation.Controllers
{
    [Authorize(Roles = "Administrador")]
    public class UsuarioController : Controller
    {
        private readonly ILogger<UsuarioController> _logger;
        private readonly IUsuarioRepository _repository;

        public UsuarioController(ILogger<UsuarioController> logger, IUsuarioRepository repository)
        {
            _logger = logger;
            _repository = repository;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult CarregarListaUsuariosIndex()
        {
            return Json(new { usuarios = _repository.SelectAll() });
        }

        public IActionResult Editar(string id)
        {
            return View(_repository.SelectById(id));
        }

        [HttpPost]
        public IActionResult Editar([Bind("Id, Username, Password, Email, FullName, Role")] Usuario model)
        {
            var usuarioCadastrado = _repository.Find(u => u.Username == model.Username && u.Id != model.Id).FirstOrDefault();

            if (usuarioCadastrado is not null)
            {
                ModelState.AddModelError("ErroEditarUsuario", "Usuário já cadastrado no sistema!");
                return View(model);
            }

            if (string.IsNullOrWhiteSpace(model.Role))
            {
                ModelState.AddModelError("ErroEditarUsuario", "Role não informada!");
                return View(model);
            }

            _repository.UpdateToEdit(model);
            return RedirectToAction("Index");
        }

        public IActionResult Deletar(string id)
        {
            return View(_repository.SelectById(id));
        }

        [HttpPost]
        public IActionResult Deletar(Usuario model)
        {
            _repository.DeleteById(model.Id ?? "");

            return RedirectToAction("Index");
        }
    }
}

src/DemoGit.Presentation/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DemoGit</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="//cdn.datatables.net/1.12.1/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DemoGit.Presentation.styles.css" asp-append-version="true" />
    
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-C5B9WH9HQW"></script>
    <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'G-C5B9WH9HQW');
    </script>
    
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DemoGit</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Produto" asp-action="Index">Produtos</a>
                        </li>                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CompraEfetivada" asp-action="Index">Histórico de Compras</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Produto" asp-action="ListaFavoritos">Produtos Favoritados</a>
                        </li>
                        @if(User.IsInRole("Administrador"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Usuario" asp-action="Index">Usuários</a>
                            </li>
                        }
                    </ul>
                    <ul class="navbar-nav navbar-right">
                        @if(!User!.Identity!.IsAuthenticated) 
                        {
                            <li class="nav-item col-12">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Index"><span class="glyphicon glyphicon-log-in"></span>Login</a>
                            </li>
                        } else
                        {
                            <li class="nav-item">
                                Seja muito bem vindo, @User.Identity.Name | <a href="/Login/LogOff/" style="color: black;"><b>LogOff</b></a>
                            </li>
                        }
                    </ul>
                </div>                
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - DemoGit.Presentation - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>